name: Setup Gator
description: 'Set up your GitHub Actions workflow with a specific version of Gatekeeper gator CLI.'
inputs:
  version:
    description: Version of gator
    required: true
    default: latest
outputs:
  gator-path:
    description: Path to the gator binary
branding:
  color: blue
  icon: code
runs:
  using: 'node20'
  main: 'dist/index.js'
